version: 3.8.5
name: Ozan Blog
description: The Manifest of brain stuck
repository: https://github.com/OzanLab/blog
url: https://ozan.web.id
author: Slamet Fauzan
timezone: Asia/Jakarta
twitter:
        username: ozanblacknes
        card: summary
logo: "assets/img/logo.png"
markdown: kramdown
theme: minima
collections:
  posts:
        permalink: "/:title/"
        output: true
  pages:
        permalink: "/:title/"
        output: true
defaults:
- scope:
        path: _posts
        type: posts
  values:
        layout: post
- scope:
        path: pages
        type: pages
  values:
        layout: page

plugins:
 - jekyll-feed
 - jekyll-seo-tag

exclude:
 - ".gitignore"
 - CNAME
 - README.md
